type KJVVerse = {
  number: number;
  text: string;
};

export const kjvReadingVerses = {
  "genesis-1": [
    { number: 1, text: "In the beginning God created the heaven and the earth." },
    { number: 2, text: "And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters." },
    { number: 3, text: "And God said, Let there be light: and there was light." },
    { number: 4, text: "And God saw the light, that it was good: and God divided the light from the darkness." },
    { number: 5, text: "And God called the light Day, and the darkness he called Night. And the evening and the morning were the first day." },
    { number: 6, text: "And God said, Let there be a firmament in the midst of the waters, and let it divide the waters from the waters." },
    { number: 7, text: "And God made the firmament, and divided the waters which were under the firmament from the waters which were above the firmament: and it was so." },
    { number: 8, text: "And God called the firmament Heaven. And the evening and the morning were the second day." },
    { number: 9, text: "And God said, Let the waters under the heaven be gathered together unto one place, and let the dry land appear: and it was so." },
    { number: 10, text: "And God called the dry land Earth; and the gathering together of the waters called he Seas: and God saw that it was good." },
    { number: 11, text: "And God said, Let the earth bring forth grass, the herb yielding seed, and the fruit tree yielding fruit after his kind, whose seed is in itself, upon the earth: and it was so." },
    { number: 12, text: "And the earth brought forth grass, and herb yielding seed after his kind, and the tree yielding fruit, whose seed was in itself, after his kind: and God saw that it was good." },
    { number: 13, text: "And the evening and the morning were the third day." },
    { number: 14, text: "And God said, Let there be lights in the firmament of the heaven to divide the day from the night; and let them be for signs, and for seasons, and for days, and years:" },
    { number: 15, text: "And let them be for lights in the firmament of the heaven to give light upon the earth: and it was so." },
    { number: 16, text: "And God made two great lights; the greater light to rule the day, and the lesser light to rule the night: he made the stars also." },
    { number: 17, text: "And God set them in the firmament of the heaven to give light upon the earth," },
    { number: 18, text: "And to rule over the day and over the night, and to divide the light from the darkness: and God saw that it was good." },
    { number: 19, text: "And the evening and the morning were the fourth day." },
    { number: 20, text: "And God said, Let the waters bring forth abundantly the moving creature that hath life, and fowl that may fly above the earth in the open firmament of heaven." },
    { number: 21, text: "And God created great whales, and every living creature that moveth, which the waters brought forth abundantly, after their kind, and every winged fowl after his kind: and God saw that it was good." },
    { number: 22, text: "And God blessed them, saying, Be fruitful, and multiply, and fill the waters in the seas, and let fowl multiply in the earth." },
    { number: 23, text: "And the evening and the morning were the fifth day." },
    { number: 24, text: "And God said, Let the earth bring forth the living creature after his kind, cattle, and creeping thing, and beast of the earth after his kind: and it was so." },
    { number: 25, text: "And God made the beast of the earth after his kind, and cattle after their kind, and every thing that creepeth upon the earth after his kind: and God saw that it was good." },
    { number: 26, text: "And God said, Let us make man in our image, after our likeness: and let them have dominion over the fish of the sea, and over the fowl of the air, and over the cattle, and over all the earth, and over every creeping thing that creepeth upon the earth." },
    { number: 27, text: "So God created man in his own image, in the image of God created he him; male and female created he them." },
    { number: 28, text: "And God blessed them, and God said unto them, Be fruitful, and multiply, and replenish the earth, and subdue it: and have dominion over the fish of the sea, and over the fowl of the air, and over every living thing that moveth upon the earth." },
    { number: 29, text: "And God said, Behold, I have given you every herb bearing seed, which is upon the face of all the earth, and every tree, in the which is the fruit of a tree yielding seed; to you it shall be for meat." },
    { number: 30, text: "And to every beast of the earth, and to every fowl of the air, and to every thing that creepeth upon the earth, wherein there is life, I have given every green herb for meat: and it was so." },
    { number: 31, text: "And God saw every thing that he had made, and, behold, it was very good. And the evening and the morning were the sixth day." },
  ],
  "john-1": [
    { number: 1, text: "In the beginning was the Word, and the Word was with God, and the Word was God." },
    { number: 2, text: "The same was in the beginning with God." },
    { number: 3, text: "All things were made by him; and without him was not any thing made that was made." },
    { number: 4, text: "In him was life; and the life was the light of men." },
    { number: 5, text: "And the light shineth in darkness; and the darkness comprehended it not." },
    { number: 6, text: "There was a man sent from God, whose name was John." },
    { number: 7, text: "The same came for a witness, to bear witness of the Light, that all men through him might believe." },
    { number: 8, text: "He was not that Light, but was sent to bear witness of that Light." },
    { number: 9, text: "That was the true Light, which lighteth every man that cometh into the world." },
    { number: 10, text: "He was in the world, and the world was made by him, and the world knew him not." },
    { number: 11, text: "He came unto his own, and his own received him not." },
    { number: 12, text: "But as many as received him, to them gave he power to become the sons of God, even to them that believe on his name:" },
    { number: 13, text: "Which were born, not of blood, nor of the will of the flesh, nor of the will of man, but of God." },
    { number: 14, text: "And the Word was made flesh, and dwelt among us, (and we beheld his glory, the glory as of the only begotten of the Father,) full of grace and truth." },
    { number: 15, text: "John bare witness of him, and cried, saying, This was he of whom I spake, He that cometh after me is preferred before me: for he was before me." },
    { number: 16, text: "And of his fulness have all we received, and grace for grace." },
    { number: 17, text: "For the law was given by Moses, but grace and truth came by Jesus Christ." },
    { number: 18, text: "No man hath seen God at any time; the only begotten Son, which is in the bosom of the Father, he hath declared him." },
    { number: 19, text: "And this is the record of John, when the Jews sent priests and Levites from Jerusalem to ask him, Who art thou?" },
    { number: 20, text: "And he confessed, and denied not; but confessed, I am not the Christ." },
    { number: 21, text: "And they asked him, What then? Art thou Elias? And he saith, I am not. Art thou that prophet? And he answered, No." },
    { number: 22, text: "Then said they unto him, Who art thou? that we may give an answer to them that sent us. What sayest thou of thyself?" },
    { number: 23, text: "He said, I am the voice of one crying in the wilderness, Make straight the way of the Lord, as said the prophet Esaias." },
    { number: 24, text: "And they which were sent were of the Pharisees." },
    { number: 25, text: "And they asked him, and said unto him, Why baptizest thou then, if thou be not that Christ, nor Elias, neither that prophet?" },
    { number: 26, text: "John answered them, saying, I baptize with water: but there standeth one among you, whom ye know not;" },
    { number: 27, text: "He it is, who coming after me is preferred before me, whose shoe's latchet I am not worthy to unloose." },
    { number: 28, text: "These things were done in Bethabara beyond Jordan, where John was baptizing." },
    { number: 29, text: "The next day John seeth Jesus coming unto him, and saith, Behold the Lamb of God, which taketh away the sin of the world." },
    { number: 30, text: "This is he of whom I said, After me cometh a man which is preferred before me: for he was before me." },
    { number: 31, text: "And I knew him not: but that he should be made manifest to Israel, therefore am I come baptizing with water." },
    { number: 32, text: "And John bare record, saying, I saw the Spirit descending from heaven like a dove, and it abode upon him." },
    { number: 33, text: "And I knew him not: but he that sent me to baptize with water, the same said unto me, Upon whom thou shalt see the Spirit descending, and remaining on him, the same is he which baptizeth with the Holy Ghost." },
    { number: 34, text: "And I saw, and bare record that this is the Son of God." },
    { number: 35, text: "Again the next day after John stood, and two of his disciples;" },
    { number: 36, text: "And looking upon Jesus as he walked, he saith, Behold the Lamb of God!" },
    { number: 37, text: "And the two disciples heard him speak, and they followed Jesus." },
    { number: 38, text: "Then Jesus turned, and saw them following, and saith unto them, What seek ye? They said unto him, Rabbi, (which is to say, being interpreted, Master,) where dwellest thou?" },
    { number: 39, text: "He saith unto them, Come and see. They came and saw where he dwelt, and abode with him that day: for it was about the tenth hour." },
    { number: 40, text: "One of the two which heard John speak, and followed him, was Andrew, Simon Peter's brother." },
    { number: 41, text: "He first findeth his own brother Simon, and saith unto him, We have found the Messias, which is, being interpreted, the Christ." },
    { number: 42, text: "And he brought him to Jesus. And when Jesus beheld him, he said, Thou art Simon the son of Jona: thou shalt be called Cephas, which is by interpretation, A stone." },
    { number: 43, text: "The day following Jesus would go forth into Galilee, and findeth Philip, and saith unto him, Follow me." },
    { number: 44, text: "Now Philip was of Bethsaida, the city of Andrew and Peter." },
    { number: 45, text: "Philip findeth Nathanael, and saith unto him, We have found him, of whom Moses in the law, and the prophets, did write, Jesus of Nazareth, the son of Joseph." },
    { number: 46, text: "And Nathanael said unto him, Can there any good thing come out of Nazareth? Philip saith unto him, Come and see." },
    { number: 47, text: "Jesus saw Nathanael coming to him, and saith of him, Behold an Israelite indeed, in whom is no guile!" },
    { number: 48, text: "Nathanael saith unto him, Whence knowest thou me? Jesus answered and said unto him, Before that Philip called thee, when thou wast under the fig tree, I saw thee." },
    { number: 49, text: "Nathanael answered and saith unto him, Rabbi, thou art the Son of God; thou art the King of Israel." },
    { number: 50, text: "Jesus answered and said unto him, Because I said unto thee, I saw thee under the fig tree, believest thou? thou shalt see greater things than these." },
    { number: 51, text: "And he saith unto him, Verily, verily, I say unto you, Hereafter ye shall see heaven open, and the angels of God ascending and descending upon the Son of man." },
  ],
  "psalms-23": [
    { number: 1, text: "The LORD is my shepherd; I shall not want." },
    { number: 2, text: "He maketh me to lie down in green pastures: he leadeth me beside the still waters." },
    { number: 3, text: "He restoreth my soul: he leadeth me in the paths of righteousness for his name's sake." },
    { number: 4, text: "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me." },
    { number: 5, text: "Thou preparest a table before me in the presence of mine enemies: thou anointest my head with oil; my cup runneth over." },
    { number: 6, text: "Surely goodness and mercy shall follow me all the days of my life: and I will dwell in the house of the LORD for ever." },
  ],
  "psalms-91": [
    { number: 1, text: "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty." },
    { number: 2, text: "I will say of the LORD, He is my refuge and my fortress: my God; in him will I trust." },
    { number: 3, text: "Surely he shall deliver thee from the snare of the fowler, and from the noisome pestilence." },
    { number: 4, text: "He shall cover thee with his feathers, and under his wings shalt thou trust: his truth shall be thy shield and buckler." },
    { number: 5, text: "Thou shalt not be afraid for the terror by night; nor for the arrow that flieth by day;" },
    { number: 6, text: "Nor for the pestilence that walketh in darkness; nor for the destruction that wasteth at noonday." },
    { number: 7, text: "A thousand shall fall at thy side, and ten thousand at thy right hand; but it shall not come nigh thee." },
    { number: 8, text: "Only with thine eyes shalt thou behold and see the reward of the wicked." },
    { number: 9, text: "Because thou hast made the LORD, which is my refuge, even the most High, thy habitation;" },
    { number: 10, text: "There shall no evil befall thee, neither shall any plague come nigh thy dwelling." },
    { number: 11, text: "For he shall give his angels charge over thee, to keep thee in all thy ways." },
    { number: 12, text: "They shall bear thee up in their hands, lest thou dash thy foot against a stone." },
    { number: 13, text: "Thou shalt tread upon the lion and adder: the young lion and the dragon shalt thou trample under feet." },
    { number: 14, text: "Because he hath set his love upon me, therefore will I deliver him: I will set him on high, because he hath known my name." },
    { number: 15, text: "He shall call upon me, and I will answer him: I will be with him in trouble; I will deliver him, and honour him." },
    { number: 16, text: "With long life will I satisfy him, and shew him my salvation." },
  ],
  "matthew-6": [
    { number: 1, text: "Take heed that ye do not your alms before men, to be seen of them: otherwise ye have no reward of your Father which is in heaven." },
    { number: 2, text: "Therefore when thou doest thine alms, do not sound a trumpet before thee, as the hypocrites do in the synagogues and in the streets, that they may have glory of men. Verily I say unto you, They have their reward." },
    { number: 3, text: "But when thou doest alms, let not thy left hand know what thy right hand doeth:" },
    { number: 4, text: "That thine alms may be in secret: and thy Father which seeth in secret himself shall reward thee openly." },
    { number: 5, text: "And when thou prayest, thou shalt not be as the hypocrites are: for they love to pray standing in the synagogues and in the corners of the streets, that they may be seen of men. Verily I say unto you, They have their reward." },
    { number: 6, text: "But thou, when thou prayest, enter into thy closet, and when thou hast shut thy door, pray to thy Father which is in secret; and thy Father which seeth in secret shall reward thee openly." },
    { number: 7, text: "But when ye pray, use not vain repetitions, as the heathen do: for they think that they shall be heard for their much speaking." },
    { number: 8, text: "Be not ye therefore like unto them: for your Father knoweth what things ye have need of, before ye ask him." },
    { number: 9, text: "After this manner therefore pray ye: Our Father which art in heaven, Hallowed be thy name." },
    { number: 10, text: "Thy kingdom come. Thy will be done in earth, as it is in heaven." },
    { number: 11, text: "Give us this day our daily bread." },
    { number: 12, text: "And forgive us our debts, as we forgive our debtors." },
    { number: 13, text: "And lead us not into temptation, but deliver us from evil: For thine is the kingdom, and the power, and the glory, for ever. Amen." },
    { number: 14, text: "For if ye forgive men their trespasses, your heavenly Father will also forgive you:" },
    { number: 15, text: "But if ye forgive not men their trespasses, neither will your Father forgive your trespasses." },
    { number: 16, text: "Moreover when ye fast, be not, as the hypocrites, of a sad countenance: for they disfigure their faces, that they may appear unto men to fast. Verily I say unto you, They have their reward." },
    { number: 17, text: "But thou, when thou fastest, anoint thine head, and wash thy face;" },
    { number: 18, text: "That thou appear not unto men to fast, but unto thy Father which is in secret: and thy Father, which seeth in secret, shall reward thee openly." },
    { number: 19, text: "Lay not up for yourselves treasures upon earth, where moth and rust doth corrupt, and where thieves break through and steal:" },
    { number: 20, text: "But lay up for yourselves treasures in heaven, where neither moth nor rust doth corrupt, and where thieves do not break through nor steal:" },
    { number: 21, text: "For where your treasure is, there will your heart be also." },
    { number: 22, text: "The light of the body is the eye: if therefore thine eye be single, thy whole body shall be full of light." },
    { number: 23, text: "But if thine eye be evil, thy whole body shall be full of darkness. If therefore the light that is in thee be darkness, how great is that darkness!" },
    { number: 24, text: "No man can serve two masters: for either he will hate the one, and love the other; or else he will hold to the one, and despise the other. Ye cannot serve God and mammon." },
    { number: 25, text: "Therefore I say unto you, Take no thought for your life, what ye shall eat, or what ye shall drink; nor yet for your body, what ye shall put on. Is not the life more than meat, and the body than raiment?" },
    { number: 26, text: "Behold the fowls of the air: for they sow not, neither do they reap, nor gather into barns; yet your heavenly Father feedeth them. Are ye not much better than they?" },
    { number: 27, text: "Which of you by taking thought can add one cubit unto his stature?" },
    { number: 28, text: "And why take ye thought for raiment? Consider the lilies of the field, how they grow; they toil not, neither do they spin:" },
    { number: 29, text: "And yet I say unto you, That even Solomon in all his glory was not arrayed like one of these." },
    { number: 30, text: "Wherefore, if God so clothe the grass of the field, which to day is, and to morrow is cast into the oven, shall he not much more clothe you, O ye of little faith?" },
    { number: 31, text: "Therefore take no thought, saying, What shall we eat? or, What shall we drink? or, Wherewithal shall we be clothed?" },
    { number: 32, text: "(For after all these things do the Gentiles seek:) for your heavenly Father knoweth that ye have need of all these things." },
    { number: 33, text: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you." },
    { number: 34, text: "Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself. Sufficient unto the day is the evil thereof." },
  ],
  "romans-8": [
    { number: 1, text: "There is therefore now no condemnation to them which are in Christ Jesus, who walk not after the flesh, but after the Spirit." },
    { number: 2, text: "For the law of the Spirit of life in Christ Jesus hath made me free from the law of sin and death." },
    { number: 3, text: "For what the law could not do, in that it was weak through the flesh, God sending his own Son in the likeness of sinful flesh, and for sin, condemned sin in the flesh:" },
    { number: 4, text: "That the righteousness of the law might be fulfilled in us, who walk not after the flesh, but after the Spirit." },
    { number: 5, text: "For they that are after the flesh do mind the things of the flesh; but they that are after the Spirit the things of the Spirit." },
    { number: 6, text: "For to be carnally minded is death; but to be spiritually minded is life and peace." },
    { number: 7, text: "Because the carnal mind is enmity against God: for it is not subject to the law of God, neither indeed can be." },
    { number: 8, text: "So then they that are in the flesh cannot please God." },
    { number: 9, text: "But ye are not in the flesh, but in the Spirit, if so be that the Spirit of God dwell in you. Now if any man have not the Spirit of Christ, he is none of his." },
    { number: 10, text: "And if Christ be in you, the body is dead because of sin; but the Spirit is life because of righteousness." },
    { number: 11, text: "But if the Spirit of him that raised up Jesus from the dead dwell in you, he that raised up Christ from the dead shall also quicken your mortal bodies by his Spirit that dwelleth in you." },
    { number: 12, text: "Therefore, brethren, we are debtors, not to the flesh, to live after the flesh." },
    { number: 13, text: "For if ye live after the flesh, ye shall die: but if ye through the Spirit do mortify the deeds of the body, ye shall live." },
    { number: 14, text: "For as many as are led by the Spirit of God, they are the sons of God." },
    { number: 15, text: "For ye have not received the spirit of bondage again to fear; but ye have received the Spirit of adoption, whereby we cry, Abba, Father." },
    { number: 16, text: "The Spirit itself beareth witness with our spirit, that we are the children of God:" },
    { number: 17, text: "And if children, then heirs; heirs of God, and joint-heirs with Christ; if so be that we suffer with him, that we may be also glorified together." },
    { number: 18, text: "For I reckon that the sufferings of this present time are not worthy to be compared with the glory which shall be revealed in us." },
    { number: 19, text: "For the earnest expectation of the creature waiteth for the manifestation of the sons of God." },
    { number: 20, text: "For the creature was made subject to vanity, not willingly, but by reason of him who hath subjected the same in hope," },
    { number: 21, text: "Because the creature itself also shall be delivered from the bondage of corruption into the glorious liberty of the children of God." },
    { number: 22, text: "For we know that the whole creation groaneth and travaileth in pain together until now." },
    { number: 23, text: "And not only they, but ourselves also, which have the firstfruits of the Spirit, even we ourselves groan within ourselves, waiting for the adoption, to wit, the redemption of our body." },
    { number: 24, text: "For we are saved by hope: but hope that is seen is not hope: for what a man seeth, why doth he yet hope for?" },
    { number: 25, text: "But if we hope for that we see not, then do we with patience wait for it." },
    { number: 26, text: "Likewise the Spirit also helpeth our infirmities: for we know not what we should pray for as we ought: but the Spirit itself maketh intercession for us with groanings which cannot be uttered." },
    { number: 27, text: "And he that searcheth the hearts knoweth what is the mind of the Spirit, because he maketh intercession for the saints according to the will of God." },
    { number: 28, text: "And we know that all things work together for good to them that love God, to them who are the called according to his purpose." },
    { number: 29, text: "For whom he did foreknow, he also did predestinate to be conformed to the image of his Son, that he might be the firstborn among many brethren." },
    { number: 30, text: "Moreover whom he did predestinate, them he also called: and whom he called, them he also justified: and whom he justified, them he also glorified." },
    { number: 31, text: "What shall we then say to these things? If God be for us, who can be against us?" },
    { number: 32, text: "He that spared not his own Son, but delivered him up for us all, how shall he not with him also freely give us all things?" },
    { number: 33, text: "Who shall lay any thing to the charge of God's elect? It is God that justifieth." },
    { number: 34, text: "Who is he that condemneth? It is Christ that died, yea rather, that is risen again, who is even at the right hand of God, who also maketh intercession for us." },
    { number: 35, text: "Who shall separate us from the love of Christ? shall tribulation, or distress, or persecution, or famine, or nakedness, or peril, or sword?" },
    { number: 36, text: "As it is written, For thy sake we are killed all the day long; we are accounted as sheep for the slaughter." },
    { number: 37, text: "Nay, in all these things we are more than conquerors through him that loved us." },
    { number: 38, text: "For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come," },
    { number: 39, text: "Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord." },
  ],
  "proverbs-3": [
    { number: 1, text: "My son, forget not my law; but let thine heart keep my commandments:" },
    { number: 2, text: "For length of days, and long life, and peace, shall they add to thee." },
    { number: 3, text: "Let not mercy and truth forsake thee: bind them about thy neck; write them upon the table of thine heart:" },
    { number: 4, text: "So shalt thou find favour and good understanding in the sight of God and man." },
    { number: 5, text: "Trust in the LORD with all thine heart; and lean not unto thine own understanding." },
    { number: 6, text: "In all thy ways acknowledge him, and he shall direct thy paths." },
    { number: 7, text: "Be not wise in thine own eyes: fear the LORD, and depart from evil." },
    { number: 8, text: "It shall be health to thy navel, and marrow to thy bones." },
    { number: 9, text: "Honour the LORD with thy substance, and with the firstfruits of all thine increase:" },
    { number: 10, text: "So shall thy barns be filled with plenty, and thy presses shall burst out with new wine." },
    { number: 11, text: "My son, despise not the chastening of the LORD; neither be weary of his correction:" },
    { number: 12, text: "For whom the LORD loveth he correcteth; even as a father the son in whom he delighteth." },
    { number: 13, text: "Happy is the man that findeth wisdom, and the man that getteth understanding." },
    { number: 14, text: "For the merchandise of it is better than the merchandise of silver, and the gain thereof than fine gold." },
    { number: 15, text: "She is more precious than rubies: and all the things thou canst desire are not to be compared unto her." },
    { number: 16, text: "Length of days is in her right hand; and in her left hand riches and honour." },
    { number: 17, text: "Her ways are ways of pleasantness, and all her paths are peace." },
    { number: 18, text: "She is a tree of life to them that lay hold upon her: and happy is every one that retaineth her." },
    { number: 19, text: "The LORD by wisdom hath founded the earth; by understanding hath he established the heavens." },
    { number: 20, text: "By his knowledge the depths are broken up, and the clouds drop down the dew." },
    { number: 21, text: "My son, let not them depart from thine eyes: keep sound wisdom and discretion:" },
    { number: 22, text: "So shall they be life unto thy soul, and grace to thy neck." },
    { number: 23, text: "Then shalt thou walk in thy way safely, and thy foot shall not stumble." },
    { number: 24, text: "When thou liest down, thou shalt not be afraid: yea, thou shalt lie down, and thy sleep shall be sweet." },
    { number: 25, text: "Be not afraid of sudden fear, neither of the desolation of the wicked, when it cometh." },
    { number: 26, text: "For the LORD shall be thy confidence, and shall keep thy foot from being taken." },
    { number: 27, text: "Withhold not good from them to whom it is due, when it is in the power of thine hand to do it." },
    { number: 28, text: "Say not unto thy neighbour, Go, and come again, and to morrow I will give; when thou hast it by thee." },
    { number: 29, text: "Devise not evil against thy neighbour, seeing he dwelleth securely by thee." },
    { number: 30, text: "Strive not with a man without cause, if he have done thee no harm." },
    { number: 31, text: "Envy thou not the oppressor, and choose none of his ways." },
    { number: 32, text: "For the froward is abomination to the LORD: but his secret is with the righteous." },
    { number: 33, text: "The curse of the LORD is in the house of the wicked: but he blesseth the habitation of the just." },
    { number: 34, text: "Surely he scorneth the scorners: but he giveth grace unto the lowly." },
    { number: 35, text: "The wise shall inherit glory: but shame shall be the promotion of fools." },
  ],
  "1-corinthians-13": [
    { number: 1, text: "Though I speak with the tongues of men and of angels, and have not charity, I am become as sounding brass, or a tinkling cymbal." },
    { number: 2, text: "And though I have the gift of prophecy, and understand all mysteries, and all knowledge; and though I have all faith, so that I could remove mountains, and have not charity, I am nothing." },
    { number: 3, text: "And though I bestow all my goods to feed the poor, and though I give my body to be burned, and have not charity, it profiteth me nothing." },
    { number: 4, text: "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up," },
    { number: 5, text: "Doth not behave itself unseemly, seeketh not her own, is not easily provoked, thinketh no evil;" },
    { number: 6, text: "Rejoiceth not in iniquity, but rejoiceth in the truth;" },
    { number: 7, text: "Beareth all things, believeth all things, hopeth all things, endureth all things." },
    { number: 8, text: "Charity never faileth: but whether there be prophecies, they shall fail; whether there be tongues, they shall cease; whether there be knowledge, it shall vanish away." },
    { number: 9, text: "For we know in part, and we prophesy in part." },
    { number: 10, text: "But when that which is perfect is come, then that which is in part shall be done away." },
    { number: 11, text: "When I was a child, I spake as a child, I understood as a child, I thought as a child: but when I became a man, I put away childish things." },
    { number: 12, text: "For now we see through a glass, darkly; but then face to face: now I know in part; but then shall I know even as also I am known." },
    { number: 13, text: "And now abideth faith, hope, charity, these three; but the greatest of these is charity." },
  ],
  "philippians-4": [
    { number: 1, text: "Therefore, my brethren dearly beloved and longed for, my joy and crown, so stand fast in the Lord, my dearly beloved." },
    { number: 2, text: "I beseech Euodias, and beseech Syntyche, that they be of the same mind in the Lord." },
    { number: 3, text: "And I intreat thee also, true yokefellow, help those women which laboured with me in the gospel, with Clement also, and with other my fellowlabourers, whose names are in the book of life." },
    { number: 4, text: "Rejoice in the Lord alway: and again I say, Rejoice." },
    { number: 5, text: "Let your moderation be known unto all men. The Lord is at hand." },
    { number: 6, text: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God." },
    { number: 7, text: "And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus." },
    { number: 8, text: "Finally, brethren, whatsoever things are true, whatsoever things are honest, whatsoever things are just, whatsoever things are pure, whatsoever things are lovely, whatsoever things are of good report; if there be any virtue, and if there be any praise, think on these things." },
    { number: 9, text: "Those things, which ye have both learned, and received, and heard, and seen in me, do: and the God of peace shall be with you." },
    { number: 10, text: "But I rejoiced in the Lord greatly, that now at the last your care of me hath flourished again; wherein ye were also careful, but ye lacked opportunity." },
    { number: 11, text: "Not that I speak in respect of want: for I have learned, in whatsoever state I am, therewith to be content." },
    { number: 12, text: "I know both how to be abased, and I know how to abound: every where and in all things I am instructed both to be full and to be hungry, both to abound and to suffer need." },
    { number: 13, text: "I can do all things through Christ which strengtheneth me." },
    { number: 14, text: "Notwithstanding ye have well done, that ye did communicate with my affliction." },
    { number: 15, text: "Now ye Philippians know also, that in the beginning of the gospel, when I departed from Macedonia, no church communicated with me as concerning giving and receiving, but ye only." },
    { number: 16, text: "For even in Thessalonica ye sent once and again unto my necessity." },
    { number: 17, text: "Not because I desire a gift: but I desire fruit that may abound to your account." },
    { number: 18, text: "But I have all, and abound: I am full, having received of Epaphroditus the things which were sent from you, an odour of a sweet smell, a sacrifice acceptable, wellpleasing to God." },
    { number: 19, text: "But my God shall supply all your need according to his riches in glory by Christ Jesus." },
    { number: 20, text: "Now unto God and our Father be glory for ever and ever. Amen." },
    { number: 21, text: "Salute every saint in Christ Jesus. The brethren which are with me greet you." },
    { number: 22, text: "All the saints salute you, chiefly they that are of Caesar's household." },
    { number: 23, text: "The grace of our Lord Jesus Christ be with you all. Amen." },
  ],
  "isaiah-40": [
    { number: 1, text: "Comfort ye, comfort ye my people, saith your God." },
    { number: 2, text: "Speak ye comfortably to Jerusalem, and cry unto her, that her warfare is accomplished, that her iniquity is pardoned: for she hath received of the LORD'S hand double for all her sins." },
    { number: 3, text: "The voice of him that crieth in the wilderness, Prepare ye the way of the LORD, make straight in the desert a highway for our God." },
    { number: 4, text: "Every valley shall be exalted, and every mountain and hill shall be made low: and the crooked shall be made straight, and the rough places plain:" },
    { number: 5, text: "And the glory of the LORD shall be revealed, and all flesh shall see it together: for the mouth of the LORD hath spoken it." },
    { number: 6, text: "The voice said, Cry. And he said, What shall I cry? All flesh is grass, and all the goodliness thereof is as the flower of the field:" },
    { number: 7, text: "The grass withereth, the flower fadeth: because the spirit of the LORD bloweth upon it: surely the people is grass." },
    { number: 8, text: "The grass withereth, the flower fadeth: but the word of our God shall stand for ever." },
    { number: 9, text: "O Zion, that bringest good tidings, get thee up into the high mountain; O Jerusalem, that bringest good tidings, lift up thy voice with strength; lift it up, be not afraid; say unto the cities of Judah, Behold your God!" },
    { number: 10, text: "Behold, the Lord GOD will come with strong hand, and his arm shall rule for him: behold, his reward is with him, and his work before him." },
    { number: 11, text: "He shall feed his flock like a shepherd: he shall gather the lambs with his arm, and carry them in his bosom, and shall gently lead those that are with young." },
    { number: 12, text: "Who hath measured the waters in the hollow of his hand, and meted out heaven with the span, and comprehended the dust of the earth in a measure, and weighed the mountains in scales, and the hills in a balance?" },
    { number: 13, text: "Who hath directed the Spirit of the LORD, or being his counsellor hath taught him?" },
    { number: 14, text: "With whom took he counsel, and who instructed him, and taught him in the path of judgment, and taught him knowledge, and shewed to him the way of understanding?" },
    { number: 15, text: "Behold, the nations are as a drop of a bucket, and are counted as the small dust of the balance: behold, he taketh up the isles as a very little thing." },
    { number: 16, text: "And Lebanon is not sufficient to burn, nor the beasts thereof sufficient for a burnt offering." },
    { number: 17, text: "All nations before him are as nothing; and they are counted to him less than nothing, and vanity." },
    { number: 18, text: "To whom then will ye liken God? or what likeness will ye compare unto him?" },
    { number: 19, text: "The workman melteth a graven image, and the goldsmith spreadeth it over with gold, and casteth silver chains." },
    { number: 20, text: "He that is so impoverished that he hath no oblation chooseth a tree that will not rot; he seeketh unto him a cunning workman to prepare a graven image, that shall not be moved." },
    { number: 21, text: "Have ye not known? have ye not heard? hath it not been told you from the beginning? have ye not understood from the foundations of the earth?" },
    { number: 22, text: "It is he that sitteth upon the circle of the earth, and the inhabitants thereof are as grasshoppers; that stretcheth out the heavens as a curtain, and spreadeth them out as a tent to dwell in:" },
    { number: 23, text: "That bringeth the princes to nothing; he maketh the judges of the earth as vanity." },
    { number: 24, text: "Yea, they shall not be planted; yea, they shall not be sown: yea, their stock shall not take root in the earth: and he shall also blow upon them, and they shall wither, and the whirlwind shall take them away as stubble." },
    { number: 25, text: "To whom then will ye liken me, or shall I be equal? saith the Holy One." },
    { number: 26, text: "Lift up your eyes on high, and behold who hath created these things, that bringeth out their host by number: he calleth them all by names by the greatness of his might, for that he is strong in power; not one faileth." },
    { number: 27, text: "Why sayest thou, O Jacob, and speakest, O Israel, My way is hid from the LORD, and my judgment is passed over from my God?" },
    { number: 28, text: "Hast thou not known? hast thou not heard, that the everlasting God, the LORD, the Creator of the ends of the earth, fainteth not, neither is weary? there is no searching of his understanding." },
    { number: 29, text: "He giveth power to the faint; and to them that have no might he increaseth strength." },
    { number: 30, text: "Even the youths shall faint and be weary, and the young men shall utterly fall:" },
    { number: 31, text: "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint." },
  ],
  "luke-15": [
    { number: 1, text: "Then drew near unto him all the publicans and sinners for to hear him." },
    { number: 2, text: "And the Pharisees and scribes murmured, saying, This man receiveth sinners, and eateth with them." },
    { number: 3, text: "And he spake this parable unto them, saying," },
    { number: 4, text: "What man of you, having an hundred sheep, if he lose one of them, doth not leave the ninety and nine in the wilderness, and go after that which is lost, until he find it?" },
    { number: 5, text: "And when he hath found it, he layeth it on his shoulders, rejoicing." },
    { number: 6, text: "And when he cometh home, he calleth together his friends and neighbours, saying unto them, Rejoice with me; for I have found my sheep which was lost." },
    { number: 7, text: "I say unto you, that likewise joy shall be in heaven over one sinner that repenteth, more than over ninety and nine just persons, which need no repentance." },
    { number: 8, text: "Either what woman having ten pieces of silver, if she lose one piece, doth not light a candle, and sweep the house, and seek diligently till she find it?" },
    { number: 9, text: "And when she hath found it, she calleth her friends and her neighbours together, saying, Rejoice with me; for I have found the piece which I had lost." },
    { number: 10, text: "Likewise, I say unto you, there is joy in the presence of the angels of God over one sinner that repenteth." },
    { number: 11, text: "And he said, A certain man had two sons:" },
    { number: 12, text: "And the younger of them said to his father, Father, give me the portion of goods that falleth to me. And he divided unto them his living." },
    { number: 13, text: "And not many days after the younger son gathered all together, and took his journey into a far country, and there wasted his substance with riotous living." },
    { number: 14, text: "And when he had spent all, there arose a mighty famine in that land; and he began to be in want." },
    { number: 15, text: "And he went and joined himself to a citizen of that country; and he sent him into his fields to feed swine." },
    { number: 16, text: "And he would fain have filled his belly with the husks that the swine did eat: and no man gave unto him." },
    { number: 17, text: "And when he came to himself, he said, How many hired servants of my father's have bread enough and to spare, and I perish with hunger!" },
    { number: 18, text: "I will arise and go to my father, and will say unto him, Father, I have sinned against heaven, and before thee," },
    { number: 19, text: "And am no more worthy to be called thy son: make me as one of thy hired servants." },
    { number: 20, text: "And he arose, and came to his father. But when he was yet a great way off, his father saw him, and had compassion, and ran, and fell on his neck, and kissed him." },
    { number: 21, text: "And the son said unto him, Father, I have sinned against heaven, and in thy sight, and am no more worthy to be called thy son." },
    { number: 22, text: "But the father said to his servants, Bring forth the best robe, and put it on him; and put a ring on his hand, and shoes on his feet:" },
    { number: 23, text: "And bring hither the fatted calf, and kill it; and let us eat, and be merry:" },
    { number: 24, text: "For this my son was dead, and is alive again; he was lost, and is found. And they began to be merry." },
    { number: 25, text: "Now his elder son was in the field: and as he came and drew nigh to the house, he heard musick and dancing." },
    { number: 26, text: "And he called one of the servants, and asked what these things meant." },
    { number: 27, text: "And he said unto him, Thy brother is come; and thy father hath killed the fatted calf, because he hath received him safe and sound." },
    { number: 28, text: "And he was angry, and would not go in: therefore came his father out, and intreated him." },
    { number: 29, text: "And he answering said to his father, Lo, these many years do I serve thee, neither transgressed I at any time thy commandment: and yet thou never gavest me a kid, that I might make merry with my friends:" },
    { number: 30, text: "But as soon as this thy son was come, which hath devoured thy living with harlots, thou hast killed for him the fatted calf." },
    { number: 31, text: "And he said unto him, Son, thou art ever with me, and all that I have is thine." },
    { number: 32, text: "It was meet that we should make merry, and be glad: for this thy brother was dead, and is alive again; and was lost, and is found." },
  ],
  "john-3": [
    { number: 1, text: "There was a man of the Pharisees, named Nicodemus, a ruler of the Jews:" },
    { number: 2, text: "The same came to Jesus by night, and said unto him, Rabbi, we know that thou art a teacher come from God: for no man can do these miracles that thou doest, except God be with him." },
    { number: 3, text: "Jesus answered and said unto him, Verily, verily, I say unto thee, Except a man be born again, he cannot see the kingdom of God." },
    { number: 4, text: "Nicodemus saith unto him, How can a man be born when he is old? can he enter the second time into his mother's womb, and be born?" },
    { number: 5, text: "Jesus answered, Verily, verily, I say unto thee, Except a man be born of water and of the Spirit, he cannot enter into the kingdom of God." },
    { number: 6, text: "That which is born of the flesh is flesh; and that which is born of the Spirit is spirit." },
    { number: 7, text: "Marvel not that I said unto thee, Ye must be born again." },
    { number: 8, text: "The wind bloweth where it listeth, and thou hearest the sound thereof, but canst not tell whence it cometh, and whither it goeth: so is every one that is born of the Spirit." },
    { number: 9, text: "Nicodemus answered and said unto him, How can these things be?" },
    { number: 10, text: "Jesus answered and said unto him, Art thou a master of Israel, and knowest not these things?" },
    { number: 11, text: "Verily, verily, I say unto thee, We speak that we do know, and testify that we have seen; and ye receive not our witness." },
    { number: 12, text: "If I have told you earthly things, and ye believe not, how shall ye believe, if I tell you of heavenly things?" },
    { number: 13, text: "And no man hath ascended up to heaven, but he that came down from heaven, even the Son of man which is in heaven." },
    { number: 14, text: "And as Moses lifted up the serpent in the wilderness, even so must the Son of man be lifted up:" },
    { number: 15, text: "That whosoever believeth in him should not perish, but have eternal life." },
    { number: 16, text: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life." },
    { number: 17, text: "For God sent not his Son into the world to condemn the world; but that the world through him might be saved." },
    { number: 18, text: "He that believeth on him is not condemned: but he that believeth not is condemned already, because he hath not believed in the name of the only begotten Son of God." },
    { number: 19, text: "And this is the condemnation, that light is come into the world, and men loved darkness rather than light, because their deeds were evil." },
    { number: 20, text: "For every one that doeth evil hateth the light, neither cometh to the light, lest his deeds should be reproved." },
    { number: 21, text: "But he that doeth truth cometh to the light, that his deeds may be made manifest, that they are wrought in God." },
    { number: 22, text: "After these things came Jesus and his disciples into the land of Judaea; and there he tarried with them, and baptized." },
    { number: 23, text: "And John also was baptizing in Aenon near to Salim, because there was much water there: and they came, and were baptized." },
    { number: 24, text: "For John was not yet cast into prison." },
    { number: 25, text: "Then there arose a question between some of John's disciples and the Jews about purifying." },
    { number: 26, text: "And they came unto John, and said unto him, Rabbi, he that was with thee beyond Jordan, to whom thou barest witness, behold, the same baptizeth, and all men come to him." },
    { number: 27, text: "John answered and said, A man can receive nothing, except it be given him from heaven." },
    { number: 28, text: "Ye yourselves bear me witness, that I said, I am not the Christ, but that I am sent before him." },
    { number: 29, text: "He that hath the bride is the bridegroom: but the friend of the bridegroom, which standeth and heareth him, rejoiceth greatly because of the bridegroom's voice: this my joy therefore is fulfilled." },
    { number: 30, text: "He must increase, but I must decrease." },
    { number: 31, text: "He that cometh from above is above all: he that is of the earth is earthly, and speaketh of the earth: he that cometh from heaven is above all." },
    { number: 32, text: "And what he hath seen and heard, that he testifieth; and no man receiveth his testimony." },
    { number: 33, text: "He that hath received his testimony hath set to his seal that God is true." },
    { number: 34, text: "For he whom God hath sent speaketh the words of God: for God giveth not the Spirit by measure unto him." },
    { number: 35, text: "The Father loveth the Son, and hath given all things into his hand." },
    { number: 36, text: "He that believeth on the Son hath everlasting life: and he that believeth not the Son shall not see life; but the wrath of God abideth on him." },
  ],
  "matthew-5": [
    { number: 1, text: "And seeing the multitudes, he went up into a mountain: and when he was set, his disciples came unto him:" },
    { number: 2, text: "And he opened his mouth, and taught them, saying," },
    { number: 3, text: "Blessed are the poor in spirit: for theirs is the kingdom of heaven." },
    { number: 4, text: "Blessed are they that mourn: for they shall be comforted." },
    { number: 5, text: "Blessed are the meek: for they shall inherit the earth." },
    { number: 6, text: "Blessed are they which do hunger and thirst after righteousness: for they shall be filled." },
    { number: 7, text: "Blessed are the merciful: for they shall obtain mercy." },
    { number: 8, text: "Blessed are the pure in heart: for they shall see God." },
    { number: 9, text: "Blessed are the peacemakers: for they shall be called the children of God." },
    { number: 10, text: "Blessed are they which are persecuted for righteousness sake: for theirs is the kingdom of heaven." },
    { number: 11, text: "Blessed are ye, when men shall revile you, and persecute you, and shall say all manner of evil against you falsely, for my sake." },
    { number: 12, text: "Rejoice, and be exceeding glad: for great is your reward in heaven: for so persecuted they the prophets which were before you." },
    { number: 13, text: "Ye are the salt of the earth: but if the salt have lost his savour, wherewith shall it be salted? it is thenceforth good for nothing, but to be cast out, and to be trodden under foot of men." },
    { number: 14, text: "Ye are the light of the world. A city that is set on an hill cannot be hid." },
    { number: 15, text: "Neither do men light a candle, and put it under a bushel, but on a candlestick; and it giveth light unto all that are in the house." },
    { number: 16, text: "Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven." },
    { number: 17, text: "Think not that I am come to destroy the law, or the prophets: I am not come to destroy, but to fulfil." },
    { number: 18, text: "For verily I say unto you, Till heaven and earth pass, one jot or one tittle shall in no wise pass from the law, till all be fulfilled." },
    { number: 19, text: "Whosoever therefore shall break one of these least commandments, and shall teach men so, he shall be called the least in the kingdom of heaven: but whosoever shall do and teach them, the same shall be called great in the kingdom of heaven." },
    { number: 20, text: "For I say unto you, That except your righteousness shall exceed the righteousness of the scribes and Pharisees, ye shall in no case enter into the kingdom of heaven." },
    { number: 21, text: "Ye have heard that it was said by them of old time, Thou shalt not kill; and whosoever shall kill shall be in danger of the judgment:" },
    { number: 22, text: "But I say unto you, That whosoever is angry with his brother without a cause shall be in danger of the judgment: and whosoever shall say to his brother, Raca, shall be in danger of the council: but whosoever shall say, Thou fool, shall be in danger of hell fire." },
    { number: 23, text: "Therefore if thou bring thy gift to the altar, and there rememberest that thy brother hath ought against thee;" },
    { number: 24, text: "Leave there thy gift before the altar, and go thy way; first be reconciled to thy brother, and then come and offer thy gift." },
    { number: 25, text: "Agree with thine adversary quickly, whiles thou art in the way with him; lest at any time the adversary deliver thee to the judge, and the judge deliver thee to the officer, and thou be cast into prison." },
    { number: 26, text: "Verily I say unto thee, Thou shalt by no means come out thence, till thou hast paid the uttermost farthing." },
    { number: 27, text: "Ye have heard that it was said by them of old time, Thou shalt not commit adultery:" },
    { number: 28, text: "But I say unto you, That whosoever looketh on a woman to lust after her hath committed adultery with her already in his heart." },
    { number: 29, text: "And if thy right eye offend thee, pluck it out, and cast it from thee: for it is profitable for thee that one of thy members should perish, and not that thy whole body should be cast into hell." },
    { number: 30, text: "And if thy right hand offend thee, cut it off, and cast it from thee: for it is profitable for thee that one of thy members should perish, and not that thy whole body should be cast into hell." },
    { number: 31, text: "It hath been said, Whosoever shall put away his wife, let him give her a writing of divorcement:" },
    { number: 32, text: "But I say unto you, That whosoever shall put away his wife, saving for the cause of fornication, causeth her to commit adultery: and whosoever shall marry her that is divorced committeth adultery." },
    { number: 33, text: "Again, ye have heard that it hath been said by them of old time, Thou shalt not forswear thyself, but shalt perform unto the Lord thine oaths:" },
    { number: 34, text: "But I say unto you, Swear not at all; neither by heaven; for it is God's throne:" },
    { number: 35, text: "Nor by the earth; for it is his footstool: neither by Jerusalem; for it is the city of the great King." },
    { number: 36, text: "Neither shalt thou swear by thy head, because thou canst not make one hair white or black." },
    { number: 37, text: "But let your communication be, Yea, yea; Nay, nay: for whatsoever is more than these cometh of evil." },
    { number: 38, text: "Ye have heard that it hath been said, An eye for an eye, and a tooth for a tooth:" },
    { number: 39, text: "But I say unto you, That ye resist not evil: but whosoever shall smite thee on thy right cheek, turn to him the other also." },
    { number: 40, text: "And if any man will sue thee at the law, and take away thy coat, let him have thy cloke also." },
    { number: 41, text: "And whosoever shall compel thee to go a mile, go with him twain." },
    { number: 42, text: "Give to him that asketh thee, and from him that would borrow of thee turn not thou away." },
    { number: 43, text: "Ye have heard that it hath been said, Thou shalt love thy neighbour, and hate thine enemy." },
    { number: 44, text: "But I say unto you, Love your enemies, bless them that curse you, do good to them that hate you, and pray for them which despitefully use you, and persecute you;" },
    { number: 45, text: "That ye may be the children of your Father which is in heaven: for he maketh his sun to rise on the evil and on the good, and sendeth rain on the just and on the unjust." },
    { number: 46, text: "For if ye love them which love you, what reward have ye? do not even the publicans the same?" },
    { number: 47, text: "And if ye salute your brethren only, what do ye more than others? do not even the publicans so?" },
    { number: 48, text: "Be ye therefore perfect, even as your Father which is in heaven is perfect." },
  ],
  "psalms-121": [
    { number: 1, text: "I will lift up mine eyes unto the hills, from whence cometh my help." },
    { number: 2, text: "My help cometh from the LORD, which made heaven and earth." },
    { number: 3, text: "He will not suffer thy foot to be moved: he that keepeth thee will not slumber." },
    { number: 4, text: "Behold, he that keepeth Israel shall neither slumber nor sleep." },
    { number: 5, text: "The LORD is thy keeper: the LORD is thy shade upon thy right hand." },
    { number: 6, text: "The sun shall not smite thee by day, nor the moon by night." },
    { number: 7, text: "The LORD shall preserve thee from all evil: he shall preserve thy soul." },
    { number: 8, text: "The LORD shall preserve thy going out and thy coming in from this time forth, and even for evermore." },
  ],
  "psalms-139": [
    { number: 1, text: "O LORD, thou hast searched me, and known me." },
    { number: 2, text: "Thou knowest my downsitting and mine uprising, thou understandest my thought afar off." },
    { number: 3, text: "Thou compassest my path and my lying down, and art acquainted with all my ways." },
    { number: 4, text: "For there is not a word in my tongue, but, lo, O LORD, thou knowest it altogether." },
    { number: 5, text: "Thou hast beset me behind and before, and laid thine hand upon me." },
    { number: 6, text: "Such knowledge is too wonderful for me; it is high, I cannot attain unto it." },
    { number: 7, text: "Whither shall I go from thy spirit? or whither shall I flee from thy presence?" },
    { number: 8, text: "If I ascend up into heaven, thou art there: if I make my bed in hell, behold, thou art there." },
    { number: 9, text: "If I take the wings of the morning, and dwell in the uttermost parts of the sea;" },
    { number: 10, text: "Even there shall thy hand lead me, and thy right hand shall hold me." },
    { number: 11, text: "If I say, Surely the darkness shall cover me; even the night shall be light about me." },
    { number: 12, text: "Yea, the darkness hideth not from thee; but the night shineth as the day: the darkness and the light are both alike to thee." },
    { number: 13, text: "For thou hast possessed my reins: thou hast covered me in my mother's womb." },
    { number: 14, text: "I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works; and that my soul knoweth right well." },
    { number: 15, text: "My substance was not hid from thee, when I was made in secret, and curiously wrought in the lowest parts of the earth." },
    { number: 16, text: "Thine eyes did see my substance, yet being unperfect; and in thy book all my members were written, which in continuance were fashioned, when as yet there was none of them." },
    { number: 17, text: "How precious also are thy thoughts unto me, O God! how great is the sum of them!" },
    { number: 18, text: "If I should count them, they are more in number than the sand: when I awake, I am still with thee." },
    { number: 19, text: "Surely thou wilt slay the wicked, O God: depart from me therefore, ye bloody men." },
    { number: 20, text: "For they speak against thee wickedly, and thine enemies take thy name in vain." },
    { number: 21, text: "Do not I hate them, O LORD, that hate thee? and am not I grieved with those that rise up against thee?" },
    { number: 22, text: "I hate them with perfect hatred: I count them mine enemies." },
    { number: 23, text: "Search me, O God, and know my heart: try me, and know my thoughts:" },
    { number: 24, text: "And see if there be any wicked way in me, and lead me in the way everlasting." },
  ],
  "ephesians-2": [
    { number: 1, text: "And you hath he quickened, who were dead in trespasses and sins;" },
    { number: 2, text: "Wherein in time past ye walked according to the course of this world, according to the prince of the power of the air, the spirit that now worketh in the children of disobedience:" },
    { number: 3, text: "Among whom also we all had our conversation in times past in the lusts of our flesh, fulfilling the desires of the flesh and of the mind; and were by nature the children of wrath, even as others." },
    { number: 4, text: "But God, who is rich in mercy, for his great love wherewith he loved us," },
    { number: 5, text: "Even when we were dead in sins, hath quickened us together with Christ, (by grace ye are saved;)" },
    { number: 6, text: "And hath raised us up together, and made us sit together in heavenly places in Christ Jesus:" },
    { number: 7, text: "That in the ages to come he might shew the exceeding riches of his grace in his kindness toward us through Christ Jesus." },
    { number: 8, text: "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God:" },
    { number: 9, text: "Not of works, lest any man should boast." },
    { number: 10, text: "For we are his workmanship, created in Christ Jesus unto good works, which God hath before ordained that we should walk in them." },
    { number: 11, text: "Wherefore remember, that ye being in time past Gentiles in the flesh, who are called Uncircumcision by that which is called the Circumcision in the flesh made by hands;" },
    { number: 12, text: "That at that time ye were without Christ, being aliens from the commonwealth of Israel, and strangers from the covenants of promise, having no hope, and without God in the world:" },
    { number: 13, text: "But now in Christ Jesus ye who sometimes were far off are made nigh by the blood of Christ." },
    { number: 14, text: "For he is our peace, who hath made both one, and hath broken down the middle wall of partition between us;" },
    { number: 15, text: "Having abolished in his flesh the enmity, even the law of commandments contained in ordinances; for to make in himself of twain one new man, so making peace;" },
    { number: 16, text: "And that he might reconcile both unto God in one body by the cross, having slain the enmity thereby:" },
    { number: 17, text: "And came and preached peace to you which were afar off, and to them that were nigh." },
    { number: 18, text: "For through him we both have access by one Spirit unto the Father." },
    { number: 19, text: "Now therefore ye are no more strangers and foreigners, but fellowcitizens with the saints, and of the household of God;" },
    { number: 20, text: "And are built upon the foundation of the apostles and prophets, Jesus Christ himself being the chief corner stone;" },
    { number: 21, text: "In whom all the building fitly framed together groweth unto an holy temple in the Lord:" },
    { number: 22, text: "In whom ye also are builded together for an habitation of God through the Spirit." },
  ],
  "james-1": [
    { number: 1, text: "James, a servant of God and of the Lord Jesus Christ, to the twelve tribes which are scattered abroad, greeting." },
    { number: 2, text: "My brethren, count it all joy when ye fall into divers temptations;" },
    { number: 3, text: "Knowing this, that the trying of your faith worketh patience." },
    { number: 4, text: "But let patience have her perfect work, that ye may be perfect and entire, wanting nothing." },
    { number: 5, text: "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him." },
    { number: 6, text: "But let him ask in faith, nothing wavering. For he that wavereth is like a wave of the sea driven with the wind and tossed." },
    { number: 7, text: "For let not that man think that he shall receive any thing of the Lord." },
    { number: 8, text: "A double minded man is unstable in all his ways." },
    { number: 9, text: "Let the brother of low degree rejoice in that he is exalted:" },
    { number: 10, text: "But the rich, in that he is made low: because as the flower of the grass he shall pass away." },
    { number: 11, text: "For the sun is no sooner risen with a burning heat, but it withereth the grass, and the flower thereof falleth, and the grace of the fashion of it perisheth: so also shall the rich man fade away in his ways." },
    { number: 12, text: "Blessed is the man that endureth temptation: for when he is tried, he shall receive the crown of life, which the Lord hath promised to them that love him." },
    { number: 13, text: "Let no man say when he is tempted, I am tempted of God: for God cannot be tempted with evil, neither tempteth he any man:" },
    { number: 14, text: "But every man is tempted, when he is drawn away of his own lust, and enticed." },
    { number: 15, text: "Then when lust hath conceived, it bringeth forth sin: and sin, when it is finished, bringeth forth death." },
    { number: 16, text: "Do not err, my beloved brethren." },
    { number: 17, text: "Every good gift and every perfect gift is from above, and cometh down from the Father of lights, with whom is no variableness, neither shadow of turning." },
    { number: 18, text: "Of his own will begat he us with the word of truth, that we should be a kind of firstfruits of his creatures." },
    { number: 19, text: "Wherefore, my beloved brethren, let every man be swift to hear, slow to speak, slow to wrath:" },
    { number: 20, text: "For the wrath of man worketh not the righteousness of God." },
    { number: 21, text: "Wherefore lay apart all filthiness and superfluity of naughtiness, and receive with meekness the engrafted word, which is able to save your souls." },
    { number: 22, text: "But be ye doers of the word, and not hearers only, deceiving your own selves." },
    { number: 23, text: "For if any be a hearer of the word, and not a doer, he is like unto a man beholding his natural face in a glass:" },
    { number: 24, text: "For he beholdeth himself, and goeth his way, and straightway forgetteth what manner of man he was." },
    { number: 25, text: "But whoso looketh into the perfect law of liberty, and continueth therein, he being not a forgetful hearer, but a doer of the work, this man shall be blessed in his deed." },
    { number: 26, text: "If any man among you seem to be religious, and bridleth not his tongue, but deceiveth his own heart, this man's religion is vain." },
    { number: 27, text: "Pure religion and undefiled before God and the Father is this, To visit the fatherless and widows in their affliction, and to keep himself unspotted from the world." },
  ],
  "mark-4": [
    { number: 35, text: "And the same day, when the even was come, he saith unto them, Let us pass over unto the other side." },
    { number: 36, text: "And when they had sent away the multitude, they took him even as he was in the ship. And there were also with him other little ships." },
    { number: 37, text: "And there arose a great storm of wind, and the waves beat into the ship, so that it was now full." },
    { number: 38, text: "And he was in the hinder part of the ship, asleep on a pillow: and they awake him, and say unto him, Master, carest thou not that we perish?" },
    { number: 39, text: "And he arose, and rebuked the wind, and said unto the sea, Peace, be still. And the wind ceased, and there was a great calm." },
    { number: 40, text: "And he said unto them, Why are ye so fearful? how is it that ye have no faith?" },
    { number: 41, text: "And they feared exceedingly, and said one to another, What manner of man is this, that even the wind and the sea obey him?" },
  ],
  "psalms-46": [
    { number: 1, text: "God is our refuge and strength, a very present help in trouble." },
    { number: 2, text: "Therefore will not we fear, though the earth be removed, and though the mountains be carried into the midst of the sea;" },
    { number: 3, text: "Though the waters thereof roar and be troubled, though the mountains shake with the swelling thereof. Selah." },
    { number: 4, text: "There is a river, the streams whereof shall make glad the city of God, the holy place of the tabernacles of the most High." },
    { number: 5, text: "God is in the midst of her; she shall not be moved: God shall help her, and that right early." },
    { number: 6, text: "The heathen raged, the kingdoms were moved: he uttered his voice, the earth melted." },
    { number: 7, text: "The LORD of hosts is with us; the God of Jacob is our refuge. Selah." },
    { number: 8, text: "Come, behold the works of the LORD, what desolations he hath made in the earth." },
    { number: 9, text: "He maketh wars to cease unto the end of the earth; he breaketh the bow, and cutteth the spear in sunder; he burneth the chariot in the fire." },
    { number: 10, text: "Be still, and know that I am God: I will be exalted among the heathen, I will be exalted in the earth." },
    { number: 11, text: "The LORD of hosts is with us; the God of Jacob is our refuge. Selah." },
  ],
  "matthew-11": [
    { number: 28, text: "Come unto me, all ye that labour and are heavy laden, and I will give you rest." },
    { number: 29, text: "Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls." },
    { number: 30, text: "For my yoke is easy, and my burden is light." },
  ],
} as const satisfies Record<string, readonly KJVVerse[]>;
